### PR TITLE
Bug/existing project cleanup on new with same name - master

### LINKED ISSUE #345: Provision app removes existing project (when existing name / key is passed to "addProject" API)
**Describe the bug**
in case a new project is created /with a different key but an *existing* name - the provision app will remove the existing project (Note/Attention: this happens only if *provision app is used thru API* and not thru the UI/frontende)

**To Reproduce**

**Expected behavior**
Error message that a project with this key / name already exists

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [2.0]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] ERROR o.o.p.c.ProjectApiController - An error occured while creating project [AHR], reason [Could not POST > htt
ps://jira.biscrum.com/rest/api/latest/project : {"errorMessages":[],"errors":{"projectName":"A project with that name already exists.","projectKey":"Project 'A....' uses this project key."}} Errorcode: 400] - but all cleaned up!
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] ERROR o.o.provision.util.rest.RestClient - Call failed: 
org.opendevstack.provision.util.exception.HttpException: Could not GET > https://x.y.z/rest/api/latest/project/AHR/permissionscheme : {"errorMessages":["No project 
could be found with key 'AHR'."],"errors":{}} Errorcode: 404
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] ERROR o.o.provision.services.JiraAdapter - Could not clean up jira project permission set AHR error: Could not G
ET > https://x.y.z/rest/api/latest/project/AHR/permissionscheme : {"errorMessages":["No project could be found with key 'AHR'."],"errors":{}} Errorcode: 404
2020-02-03 06:34:39 loggerFileName=AHR [http-nio-8080-exec-10] DEBUG o.o.provision.services.JiraAdapter - Cleanup done - status: 0 components are left ..“
```

**Additional context**
This is a major bug - introduced with cleanup (in 2.o)

https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/controller/ProjectApiController.java#L155
throws an exception that is caught at 
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/controller/ProjectApiController.java#L198
which causes rollback / delete

### PR DESCRIPTION
**Pull request by clemensutschig**
fixes #345  for master

### CODE REVIEW

File: src/main/java/org/opendevstack/provision/controller/ProjectApiController.java [hunk 1]
```diff
@@ -195,6 +196,9 @@
       mailAdapter.notifyUsersAboutProject(newProject);
 
       return ResponseEntity.ok().body(newProject);
+    } catch (ProjectAlreadyExistsException exAlreadyExists) {
+      return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
+          .body(exAlreadyExists.getMessage());
     } catch (Exception exProvisionNew) {
       Map<CLEANUP_LEFTOVER_COMPONENTS, Integer> cleanupResults =
```
Comment (stitakis) [inline src/main/java/org/opendevstack/provision/controller/ProjectApiController.java]: Potentially any other exception than ```ProjectAlreadyExistsException``` happening above will lead to this catch block. While this fix and this one #330 helps to reduce the number of unexpected situations, the ```cleanup()``` could still be unexpected triggered. For example, any change/mistake in future implementation of the used dependencies whithin the try/catch block (e.g. mailAdapter, JiraAdatper, etc...) could thrown an exception and trigger the ```cleanup`` method. This change as a bug fix looks ok for me so far.
Additionally, I think we need redesign a bit the project provision flow to make it more resilient and operations ready. I propose therefore (and I'll create the corresponding issue) to: 
- not remove left over components in case of exception" but mark them for deletion and 
- wrap the project creation flow in a task
- create a screen that shows list of tasks with its status (error description), so admin do not need to dig into the log file to find the error descriptoin
- provide posibility(buttons) for retry (complete task) or cleanup
@clemensutschig @metmajer your thoughs?

**Comment by clemensutschig** [comment]
@stitakis  - with you on this .. but this is the quick fix ... (to ensure we can still use "rollback") .. you ok to merge?

File: src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java [hunk 2]
```diff
@@ -226,10 +226,20 @@ public void addProjectAgainstExistingOne() throws Exception {
...
+                    CoreMatchers.containsString(
+                        "("
+                            + data.projectKey
+                            + ") or name "
+                            + "("
+                            + data.projectName
+                            + ") already exists")));
+
+    // ensure that cleanup was NOT called
+    Mockito.verify(jiraAdapter, times(0)).cleanup(isNotNull(), isNotNull());
```
Comment (stitakis) [inline src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java]: these lines could be added to ensure not adapter was called:
```
    Mockito.verify(bitbucketAdapter, times(0)).cleanup(isNotNull(), isNotNull());
    Mockito.verify(confluenceAdapter, times(0)).cleanup(isNotNull(), isNotNull());
    Mockito.verify(jenkinsPipelineAdapter, times(0)).cleanup(isNotNull(), isNotNull());
    Mockito.verify(mailAdapter, times(0)).notifyUsersAboutProject(isNotNull());
```

**Comment by stitakis** [comment]
@clemensutschig yes, I have approved it
