### PR TITLE
fixes invalid chars in component id: underscore, dots and numbers are not valid chars

### LINKED ISSUE #175: fe-angular quickstarter fails with certain names (fe-angular-7)
08:22:22 | + echo 'generate project'
-- | --
08:22:22 | + sudo docker run --rm -v /tmp/rundeck_560954ef-d245-456c-9460-6c592c9d7784_870:/data ng new fe-angular-7 --style=scss --skip-git --skip-install
08:22:24 | Project name "fe-angular-7" is not valid. `New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.`
08:22:24 | fe-angular-7

### LINKED ISSUE #465: underscore in component name causes provision failure
1.  In a new project - create a component named `docker_plain` based on docker plain quickstarter - for some reason the project's webhook proxy secret is not taken, but rather that global trigger secret `openshift` and hence component provisioning fails (401 unauthorized from webhook proxy)

```
org.opendevstack.provision.util.exception.HttpException: Could not POST > https://.../build?trigger_secret=openshift&jenkinsfile_path=delete-components/Jenkinsfile&component=ods-corejob-docker_test  : Not authorized
 Errorcode: 401
	at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:64)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.prepareAndExecuteJob(JenkinsPipelineAdapter.java:348)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.runAdminJob(JenkinsPipelineAdapter.java:542)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.lambda$cleanupQuickstartersOnly$6(JenkinsPipelineAdapter.java:512)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.IntPipeline.reduce(Unknown Source)
	at java.base/java.util.stream.IntPipeline.sum(Unknown Source)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.cleanupQuickstartersOnly(JenkinsPipelineAdapter.java:519)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.cleanup(JenkinsPipelineAdapter.java:485)
	at org.opendevstack.provision.controller.ProjectApiController.cleanup(ProjectApiController.java:901)
	at org.opendevstack.provision.controller.ProjectApiController.updateProject(ProjectApiController.java:448)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

```

For the record, other component names for the same component do work ::)

@metmajer - fyi

### PR DESCRIPTION
**Pull request by stitakis**
fixes #175 
fixes #465

### CODE REVIEW

File: src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java [hunk 1]
```diff
@@ -27,16 +27,13 @@
  */
 public class OpenProjectDataValidator {
   /**
-   * This regex matches kubernetes label naming definition.
-   *
-   * <p>Valid name starts with Alphanumeric and dashes, with dashes (-), underscores (_), dots (.),
-   * and alphanumerics between
+   * Valid name starts with alpha chars and only dashes (-) in between are allowed. It is more
+   * restrictive than kubernetes label syntax
```
Comment (michaelsauter) [inline src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java:31]: Would be great to mention / link to the reason here.
